---
abstract: 'Deflates and inflates Moose attributes to and from a string'
author:
  - 'Moritz Onken'
build_requires:
  Carp: 0
  DateTime: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  MooseX::Types: 0
  MooseX::Types::Moose: 0
  MooseX::Types::Structured: 0
  Scalar::Util: 0
  Test::Exception: 0
  Test::More: 0.94
  perl: 5.004
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101612, CPAN::Meta::Converter version 2.101610'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Attribute-Deflator
provides:
  MooseX::Attribute::Deflator:
    file: lib/MooseX/Attribute/Deflator.pm
    version: 1.101670
  MooseX::Attribute::Deflator::Meta::Role::Attribute:
    file: lib/MooseX/Attribute/Deflator/Meta/Role/Attribute.pm
    version: 1.101670
  MooseX::Attribute::Deflator::Moose:
    file: lib/MooseX/Attribute/Deflator/Moose.pm
    version: 1.101670
  MooseX::Attribute::Deflator::Registry:
    file: lib/MooseX/Attribute/Deflator/Registry.pm
    version: 1.101670
  MooseX::Attribute::Deflator::Structured:
    file: lib/MooseX/Attribute/Deflator/Structured.pm
    version: 1.101670
  MooseX::Attribute::LazyInflator:
    file: lib/MooseX/Attribute/LazyInflator.pm
    version: 1.101670
  MooseX::Attribute::LazyInflator::Meta::Role::Attribute:
    file: lib/MooseX/Attribute/LazyInflator/Meta/Role/Attribute.pm
    version: 1.101670
  MooseX::Attribute::LazyInflator::Meta::Role::Method::Accessor:
    file: lib/MooseX/Attribute/LazyInflator/Meta/Role/Method/Accessor.pm
    version: 1.101670
  MooseX::Attribute::LazyInflator::Meta::Role::Method::Constructor:
    file: lib/MooseX/Attribute/LazyInflator/Meta/Role/Method/Constructor.pm
    version: 1.101670
  MooseX::Attribute::LazyInflator::Role::Class:
    file: lib/MooseX/Attribute/LazyInflator/Role/Class.pm
    version: 1.101670
requires:
  JSON: 0
  Moose: 1.01
  Moose::Exporter: 0
  Moose::Meta::Method::Accessor: 0
  Moose::Role: 0
  Moose::Util: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=MooseX-Attribute-Deflator
  homepage: http://search.cpan.org/dist/MooseX-Attribute-Deflator/
  repository: http://github.com/monken/p5-moosex-attribute-deflator
version: 1.101670
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::AutoVersion
      name: '@JQUELIN/AutoVersion'
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@JQUELIN/GatherDir'
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::CompileTests
      name: '@JQUELIN/CompileTests'
      version: 1.101600
    -
      class: Dist::Zilla::Plugin::CriticTests
      name: '@JQUELIN/CriticTests'
      version: 1.100140
    -
      class: Dist::Zilla::Plugin::HasVersionTests
      name: '@JQUELIN/HasVersionTests'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::KwaliteeTests
      name: '@JQUELIN/KwaliteeTests'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::MetaTests
      name: '@JQUELIN/MetaTests'
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::MinimumVersionTests
      name: '@JQUELIN/MinimumVersionTests'
      version: 1.101421
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@JQUELIN/PodCoverageTests'
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@JQUELIN/PodSyntaxTests'
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::PortabilityTests
      name: '@JQUELIN/PortabilityTests'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::ReportVersions
      name: '@JQUELIN/ReportVersions'
      version: 1.101600
    -
      class: Dist::Zilla::Plugin::UnusedVarsTests
      name: '@JQUELIN/UnusedVarsTests'
      version: 1.100860
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@JQUELIN/PruneCruft'
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@JQUELIN/ManifestSkip'
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::AutoPrereq
      name: '@JQUELIN/AutoPrereq'
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@JQUELIN/ExtraTests'
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@JQUELIN/NextRelease'
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@JQUELIN/PkgVersion'
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@JQUELIN/PodWeaver'
      version: 3.100710
    -
      class: Dist::Zilla::Plugin::Prepender
      name: '@JQUELIN/Prepender'
      version: 1.101590
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@JQUELIN/ExecDir'
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@JQUELIN/ShareDir'
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::Bugtracker
      name: '@JQUELIN/Bugtracker'
      version: 1.101490
    -
      class: Dist::Zilla::Plugin::Homepage
      name: '@JQUELIN/Homepage'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::Repository
      name: '@JQUELIN/Repository'
      version: 0.13
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      name: '@JQUELIN/MetaProvides::Package'
      version: 1.10027802
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@JQUELIN/MetaConfig'
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::License
      name: '@JQUELIN/License'
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@JQUELIN/MetaYAML'
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::ModuleBuild
      name: '@JQUELIN/ModuleBuild'
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@JQUELIN/Readme'
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@JQUELIN/Manifest'
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::CheckChangeLog
      name: '@JQUELIN/CheckChangeLog'
      version: 0.01
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@JQUELIN/UploadToCPAN'
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@JQUELIN/Git/Check'
      version: 1.101330
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@JQUELIN/Git/Commit'
      version: 1.101330
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@JQUELIN/Git/Tag'
      version: 1.101330
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@JQUELIN/Git/Push'
      version: 1.101330
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.101612
  zilla:
    class: Dist::Zilla
    config:
      is_trial: 0
    version: 4.101612
