---
abstract: 'Deflates and inflates Moose attributes to and from a string'
author:
  - 'Moritz Onken'
build_requires:
  Carp: 0
  DateTime: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Moose::Util::TypeConstraints: 0
  MooseX::Types: 0
  MooseX::Types::Moose: 0
  MooseX::Types::Structured: 0
  Scalar::Util: 0
  Test::Exception: 0
  Test::More: 0.94
  perl: 5.004
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102341, CPAN::Meta::Converter version 2.102400'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Attribute-Deflator
provides:
  MooseX::Attribute::Deflator:
    file: lib/MooseX/Attribute/Deflator.pm
    version: 1.130000
  MooseX::Attribute::Deflator::Meta::Role::Attribute:
    file: lib/MooseX/Attribute/Deflator/Meta/Role/Attribute.pm
    version: 1.130000
  MooseX::Attribute::Deflator::Moose:
    file: lib/MooseX/Attribute/Deflator/Moose.pm
    version: 1.130000
  MooseX::Attribute::Deflator::Registry:
    file: lib/MooseX/Attribute/Deflator/Registry.pm
    version: 1.130000
  MooseX::Attribute::Deflator::Structured:
    file: lib/MooseX/Attribute/Deflator/Structured.pm
    version: 1.130000
  MooseX::Attribute::LazyInflator:
    file: lib/MooseX/Attribute/LazyInflator.pm
    version: 1.130000
  MooseX::Attribute::LazyInflator::Meta::Role::Attribute:
    file: lib/MooseX/Attribute/LazyInflator/Meta/Role/Attribute.pm
    version: 1.130000
  MooseX::Attribute::LazyInflator::Meta::Role::Method::Accessor:
    file: lib/MooseX/Attribute/LazyInflator/Meta/Role/Method/Accessor.pm
    version: 1.130000
  MooseX::Attribute::LazyInflator::Meta::Role::Method::Constructor:
    file: lib/MooseX/Attribute/LazyInflator/Meta/Role/Method/Constructor.pm
    version: 1.130000
  MooseX::Attribute::LazyInflator::Role::Class:
    file: lib/MooseX/Attribute/LazyInflator/Role/Class.pm
    version: 1.130000
requires:
  Data::Dumper: 0
  JSON: 0
  Moose: 1.15
  Moose::Exporter: 0
  Moose::Meta::Method::Accessor: 0
  Moose::Role: 0
  Moose::Util: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=MooseX-Attribute-Deflator
  homepage: http://search.cpan.org/dist/MooseX-Attribute-Deflator/
  repository: http://github.com/monken/p5-moosex-attribute-deflator
version: 1.130000
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@Filter/GatherDir'
      version: 4.102341
    -
      class: Dist::Zilla::Plugin::CompileTests
      name: '@Filter/CompileTests'
      version: 1.101800
    -
      class: Dist::Zilla::Plugin::CriticTests
      name: '@Filter/CriticTests'
      version: 1.102280
    -
      class: Dist::Zilla::Plugin::HasVersionTests
      name: '@Filter/HasVersionTests'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::KwaliteeTests
      name: '@Filter/KwaliteeTests'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::MetaTests
      name: '@Filter/MetaTests'
      version: 4.102341
    -
      class: Dist::Zilla::Plugin::MinimumVersionTests
      name: '@Filter/MinimumVersionTests'
      version: 1.101421
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@Filter/PodCoverageTests'
      version: 4.102341
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@Filter/PodSyntaxTests'
      version: 4.102341
    -
      class: Dist::Zilla::Plugin::PortabilityTests
      name: '@Filter/PortabilityTests'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::ReportVersions
      name: '@Filter/ReportVersions'
      version: 1.102460
    -
      class: Dist::Zilla::Plugin::UnusedVarsTests
      name: '@Filter/UnusedVarsTests'
      version: 1.100860
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Filter/PruneCruft'
      version: 4.102341
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Filter/ManifestSkip'
      version: 4.102341
    -
      class: Dist::Zilla::Plugin::AutoPrereq
      name: '@Filter/AutoPrereq'
      version: 4.102341
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@Filter/ExtraTests'
      version: 4.102341
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@Filter/NextRelease'
      version: 4.102341
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@Filter/PkgVersion'
      version: 4.102341
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@Filter/PodWeaver'
      version: 3.101640
    -
      class: Dist::Zilla::Plugin::Prepender
      name: '@Filter/Prepender'
      version: 1.101590
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Filter/ExecDir'
      version: 4.102341
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Filter/ShareDir'
      version: 4.102341
    -
      class: Dist::Zilla::Plugin::Bugtracker
      name: '@Filter/Bugtracker'
      version: 1.102670
    -
      class: Dist::Zilla::Plugin::Homepage
      name: '@Filter/Homepage'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::Repository
      name: '@Filter/Repository'
      version: 0.14
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      name: '@Filter/MetaProvides::Package'
      version: 1.11034304
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Filter/MetaConfig'
      version: 4.102341
    -
      class: Dist::Zilla::Plugin::License
      name: '@Filter/License'
      version: 4.102341
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Filter/MetaYAML'
      version: 4.102341
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@Filter/MetaJSON'
      version: 4.102341
    -
      class: Dist::Zilla::Plugin::ModuleBuild
      name: '@Filter/ModuleBuild'
      version: 4.102341
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@Filter/Readme'
      version: 4.102341
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Filter/Manifest'
      version: 4.102341
    -
      class: Dist::Zilla::Plugin::CheckChangeLog
      name: '@Filter/CheckChangeLog'
      version: 0.01
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Filter/UploadToCPAN'
      version: 4.102341
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@Filter/Git/Check'
      version: 1.102430
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@Filter/Git/Commit'
      version: 1.102430
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@Filter/Git/Tag'
      version: 1.102430
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@Filter/Git/Push'
      version: 1.102430
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.102341
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.102341
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.102341
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.102341
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.102341
